# Generated by Django 4.0.4 on 2022-04-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_name_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
